/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Apr 16, 2011, 10:50:04 AM
 */

package GUI;

/**
 *
 * @author benlavery
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbGameStyle = new javax.swing.JComboBox();
        lblGameStyle = new javax.swing.JLabel();
        lblMaxShots = new javax.swing.JLabel();
        chkRicochet = new javax.swing.JCheckBox();
        chkJumping = new javax.swing.JCheckBox();
        chkSpanOnBuilding = new javax.swing.JCheckBox();
        chkDieOnTeamKill = new javax.swing.JCheckBox();
        lblMaxTeamKills = new javax.swing.JLabel();
        chkDisableBots = new javax.swing.JCheckBox();
        lblMaxPlayerScore = new javax.swing.JLabel();
        lblMaxTeamScore = new javax.swing.JLabel();
        lblGameTime = new javax.swing.JLabel();
        chkManuallyStartTimedGame = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        lblMaxPlayers = new javax.swing.JLabel();
        spnMaxShots = new javax.swing.JSpinner();
        spnMaxTeamKills = new javax.swing.JSpinner();
        spnMaxPlayerScore = new javax.swing.JSpinner();
        spnMaxTeamScore = new javax.swing.JSpinner();
        spnGameTime = new javax.swing.JSpinner();
        spnMaxPlayers = new javax.swing.JSpinner();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BZFlag Server GUI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTabbedPane1.setAutoscrolls(true);

        jPanel1.setAutoscrolls(true);

        cmbGameStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free for all", "Capture the flag", "Rabbit based on score", "Rabbit based on killer", "Rabbit random" }));
        cmbGameStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGameStyleActionPerformed(evt);
            }
        });

        lblGameStyle.setText("Game Style");

        lblMaxShots.setText("Max. Shots before reload");

        chkRicochet.setText("Allow shots to ricochet");
        chkRicochet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRicochetActionPerformed(evt);
            }
        });

        chkJumping.setText("Allow jumping");
        chkJumping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkJumpingActionPerformed(evt);
            }
        });

        chkSpanOnBuilding.setText("Spawn tanks on buildings");

        chkDieOnTeamKill.setSelected(true);
        chkDieOnTeamKill.setText("Die on team kill");

        lblMaxTeamKills.setText("Kick on percentage of team kills");

        chkDisableBots.setText("Disable bots");

        lblMaxPlayerScore.setText("Max player score");

        lblMaxTeamScore.setText("Max team score");

        lblGameTime.setText("Game time limit (in seconds)");

        chkManuallyStartTimedGame.setText("Manually start timed game");

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Auto-team");

        lblMaxPlayers.setText("Max number of players");

        spnMaxShots.setModel(new javax.swing.SpinnerNumberModel(5, 1, 50, 1));

        spnMaxTeamKills.setModel(new javax.swing.SpinnerNumberModel(32, 1, 100, 1));

        spnMaxPlayerScore.setModel(new javax.swing.SpinnerNumberModel(100, 1, 1000, 1));

        spnMaxTeamScore.setModel(new javax.swing.SpinnerNumberModel(250, 1, 2500, 1));

        spnGameTime.setModel(new javax.swing.SpinnerNumberModel(3600, 60, 9999, 1));

        spnMaxPlayers.setModel(new javax.swing.SpinnerNumberModel(12, 2, 50, 1));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblGameStyle)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cmbGameStyle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(spnMaxShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblMaxShots)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(spnMaxPlayerScore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblMaxPlayerScore)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(spnMaxTeamScore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblMaxTeamScore)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .add(spnGameTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(lblGameTime))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                            .add(spnMaxTeamKills, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(lblMaxTeamKills)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(spnMaxPlayers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblMaxPlayers)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 72, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(chkSpanOnBuilding)
                    .add(chkJumping)
                    .add(chkRicochet)
                    .add(chkDieOnTeamKill)
                    .add(chkDisableBots)
                    .add(chkManuallyStartTimedGame)
                    .add(jCheckBox3))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(chkRicochet)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkJumping)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkSpanOnBuilding)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkDieOnTeamKill)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkDisableBots)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(chkManuallyStartTimedGame)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox3))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblGameStyle)
                            .add(cmbGameStyle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, spnMaxShots, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblMaxShots))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(spnMaxTeamKills, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblMaxTeamKills))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(spnMaxPlayerScore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblMaxPlayerScore))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(spnMaxTeamScore, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblMaxTeamScore))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(spnGameTime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblGameTime))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(spnMaxPlayers, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblMaxPlayers))))
                .add(89, 89, 89))
        );

        jTabbedPane1.addTab("Game Play", jPanel1);

        btnPlay.setText("Play");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnPlay))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 372, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 27, Short.MAX_VALUE)
                .add(btnPlay)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkJumpingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJumpingActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkJumpingActionPerformed

    private void chkRicochetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRicochetActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkRicochetActionPerformed

    private void cmbGameStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGameStyleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbGameStyleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JCheckBox chkDieOnTeamKill;
    private javax.swing.JCheckBox chkDisableBots;
    private javax.swing.JCheckBox chkJumping;
    private javax.swing.JCheckBox chkManuallyStartTimedGame;
    private javax.swing.JCheckBox chkRicochet;
    private javax.swing.JCheckBox chkSpanOnBuilding;
    private javax.swing.JComboBox cmbGameStyle;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblGameStyle;
    private javax.swing.JLabel lblGameTime;
    private javax.swing.JLabel lblMaxPlayerScore;
    private javax.swing.JLabel lblMaxPlayers;
    private javax.swing.JLabel lblMaxShots;
    private javax.swing.JLabel lblMaxTeamKills;
    private javax.swing.JLabel lblMaxTeamScore;
    private javax.swing.JSpinner spnGameTime;
    private javax.swing.JSpinner spnMaxPlayerScore;
    private javax.swing.JSpinner spnMaxPlayers;
    private javax.swing.JSpinner spnMaxShots;
    private javax.swing.JSpinner spnMaxTeamKills;
    private javax.swing.JSpinner spnMaxTeamScore;
    // End of variables declaration//GEN-END:variables

}
